[terminal.shell]
program = "/opt/homebrew/bin/fish"
# program = "zellij"
# args = ["-l", "welcome"]

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
size = 14

[window]
option_as_alt = "OnlyRight"

[keyboard]
bindings = [
  { key = "c", mods = "Command", action = "Copy" },
  { key = "Back", mods = "Command", chars = "\u0015" },
  { key = "รง", mods = "Command", chars = "\u0010\u0077" },
  { key = "s", mods = "Command", chars = "\u00D2" },
  { key = "k", mods = "Shift | Command", chars = "\u00CB" },
]
