[shell]
program = "/opt/homebrew/bin/fish"

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
size = 14

[window]
option_as_alt = "OnlyRight"

[keyboard]
bindings = [{ key = "c", mods = "Command", action = "Copy" }]
