theme = "gruvbox_dark_soft"

[editor]
auto-format = true
auto-completion = true
bufferline = "multiple"
line-number = "relative"
rulers = [120]
text-width = 80
end-of-line-diagnostics = "hint"
true-color = true

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.soft-wrap]
enable = true

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "╎"

[editor.file-picker]
hidden = false
parents = false
git-ignore = true

[editor.lsp]
display-inlay-hints = true

[editor.statusline]
center = ["version-control"]
right = [
  "diagnostics",
  "selections",
  "primary-selection-length",
  "register",
  "position",
  "file-encoding",
]

[keys.normal]
C-up = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
C-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-e = [
  "search_selection_detect_word_boundaries",
  "extend_search_next"
]  # add to selection the next match of the current selection
C-r = [":reload-all"]  # reload all files from disk
Cmd-s = [":write"]
Cmd-k = [":format"]
space.i = [":toggle-option lsp.display-inlay-hints"]  # Toggle inlay hints
F1 = [":sh floating-lazygit"]
F2 = [":sh floating-yazi"]
F3 = [":sh floating-serpl"]

"S-tab" = ["jump_backward"]
X = [
  "extend_line_up",
  "extend_to_line_bounds"
]  # move line selection up (unselect or select upwards)

[keys.insert]
C-space = "completion"
