
theme = "base16_transparent"

[editor]
line-number = "relative"
bufferline = "always"
auto-format = true

[keys.normal]
C-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
