[[language]]
name = "toml"
auto-format = true
language-servers = ["tombi"]

[language-server.pylsp.config.pylsp]
plugins.ruff.enabled = true
plugins.black.enabled = true

[language-server.rust-analyzer.config]
check.command = "clippy"
