use-grammars = { except = ["gemini", "perl"] }

[[language]]
name = "prolog"
grammar = "prolog"

[[grammar]]
name = "prolog"
source = { path = "/Users/nikita/Programming/tree-sitter-prolog" }

[[language]]
name = "racket"
formatter = { command = "raco", args = ["fmt"] }
auto-format = true

[language.auto-pairs]
'(' = ')'
'[' = ']'
'"' = '"'

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "haskell"
auto-format = true
formatter = { command = "hindent" }
