use-grammars = { except = [ "gemini", "perl" ] }

[[language]]
name = "prolog"
grammar = "prolog"

[[grammar]]
name = "prolog"
source = {path="/Users/nikita/Programming/tree-sitter-prolog"}

[[language]]
name = "racket"

[language.auto-pairs]
'(' = ')'
'[' = ']'

[[language]]
name = "racket"
formatter = { command = "raco fmt" }
